
# ███████╗████████╗ █████╗ ██████╗ ███████╗██╗  ██╗██╗██████╗
# ██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝██║  ██║██║██╔══██╗
# ███████╗   ██║   ███████║██████╔╝███████╗███████║██║██████╔╝
# ╚════██║   ██║   ██╔══██║██╔══██╗╚════██║██╔══██║██║██╔═══╝
# ███████║   ██║   ██║  ██║██║  ██║███████║██║  ██║██║██║
# ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝
# The minimal, blazing-fast, and infinitely customizable prompt
# https://starship.rs

[line_break]
disabled = true
[character]
success_symbol = "[](white)"
error_symbol = "[](red)"
vicmd_symbol = "[](green)"

[directory]
style = "blue bold"
home_symbol = " "

[package]
disabled = true 

[username]
style_user = 'yellow bold'
format = '[$user]($style) '
show_always = true
disabled = false

[hostname]
disabled = true

[aws]
disabled = true

[git_branch]
symbol = 'git'
format = 'on [$symbol$branch(:$remote_branch)]($style) '

